### ISSUE TITLE
[Refactor] API For Uploading Image.

### ISSUE THREAD

**Issue by danielngo99** [DucTran999/fashion-shop#70]
**Description**
In version 1.0.1, the resource used for uploading the images is **'uploadService'** this name should be changed to **'upload'**. All related must be updated after the change.

**Task lists:**
- [x] Change name to upload
- [x] Update related services
- [x] Test after the change.
